const express = require('express')
const router = express.Router()
const car_controller = require('../controller/car_controller')
const user_controller = require('../controller/user_controller')
const comment_controller = require('../controller/comment_controller')

router.get('/cars', car_controller.showCars)
router.post('/cars', user_controller.isLoggedIn, car_controller.createCar)
router.get('/cars/new', user_controller.isLoggedIn, car_controller.addCar)
router.get('/cars/:id', car_controller.showOne)
router.get('/cars/:id/edit', user_controller.isOwner, car_controller.showEditForm)
router.put('/cars/:id', user_controller.isOwner, car_controller.editCar)
router.delete('/cars/:id', user_controller.isOwner, car_controller.destroyCar)
router.get('/cars/:id/comments/new', user_controller.isLoggedIn, comment_controller.newCommentForm)
router.post('/cars/:id/comments', user_controller.isLoggedIn, comment_controller.addComment)
router.get('/cars/:id/comments/:comment_id/edit', user_controller.isCommentOwner, comment_controller.editCommentForm)
router.put('/cars/:id/comments/:comment_id', user_controller.isCommentOwner, comment_controller.editComment)
router.delete('/cars/:id/comments/:comment_id', user_controller.isCommentOwner, comment_controller.deleteComment)
module.exports = router